/* ESSAS FUNÇÕES SERVIRAM APENAS NA PÁGINA DE PACIENTES */
function limparCampos(){
	document.getElementById('data').value = ''
	document.getElementById('hora').value = ''
	document.getElementById('alojamento').value = ''
	document.getElementById('clinica').value = ''
	document.getElementById('has').value = ''
	document.getElementById('dm').value = ''
	document.getElementById('dac').value = ''
	document.getElementById('cirurgia').value = ''
	document.getElementById('alergia').value = ''
	document.getElementById('medicamentos').value = ''
	document.getElementById('pa').value = ''
	document.getElementById('pulso').value = ''
	document.getElementById('temp').value = ''
	document.getElementById('glicemia').value = ''
	document.getElementById('peso').value = ''
	document.getElementById('altura').value = ''
	document.getElementById('saturacao').value = ''
	document.getElementById('historico').value = ''
	document.getElementById('prescricao').value = ''
	document.getElementById('anotacao').value = ''
	document.getElementById('retorno').value = ''
	document.getElementById('hd').value = ''
	document.getElementById('cid').value = ''
}